version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: X3blogo
      POSTGRES_DB: blogo
      POSTGRES_PASSWORD: 'blogo-00BC7ddAa54cpB'

  blogo:
    image: rmsubekti/blogo:master
    restart: unless-stopped
    environment:
      POSTGRES_USER: X3blogo
      POSTGRES_DB: blogo # Same as postgres environment
      POSTGRES_PASSWORD: 'blogo-00BC7ddAa54cpB' # Same as postgres environment
      POSTGRES_HOSTNAME: db
      HOSTNAME: localhost #192.168.192.199 or domain.com
    ports:
      - 80:80
    depends_on:
      - db